name: recipes_flutter_demo
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0
  connectivity_plus: ^6.1.0
  dio: ^5.7.0
  riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

scripts:
  build_runner: "flutter pub run build_runner build --delete-conflicting-outputs && flutter pub get"
  build_runner:watch: "flutter pub run build_runner watch --delete-conflicting-outputs"
  fix: "dart fix --dry-run"

flutter:
  uses-material-design: true
